package com.kharazmi.helpdesk.Repository;

import com.kharazmi.helpdesk.Model.RoleModel;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 13/04/2019
*/
@Repository
public interface RoleModelRepository extends JpaRepository<RoleModel, Integer>, JpaSpecificationExecutor<RoleModel> {

}
