package com.kharazmi.helpdesk.Repository;

import com.kharazmi.helpdesk.Model.VerifyphonenumberModel;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 19/04/2019
*/
@Repository
public interface VerifyphonenumberModelRepository extends JpaRepository<VerifyphonenumberModel, Integer>, JpaSpecificationExecutor<VerifyphonenumberModel> {

    @Query(value = "select * from verifyPhoneNumber as r where r.phoneNumber =phoneNumber", nativeQuery = true)
    VerifyphonenumberModel findPhoneNumber(@Param("phoneNumber") String phoneNumber);
}
